export const careerSkillOptions = [
  "Marketing",
  "Growth",
  "Sales",
  "SQL",
  "Python",
  "Excel",
  "Google Analytics",
  "GA4",
  "Meta Ads",
  "Google Ads",
  "HubSpot",
  "Salesforce",
  "SEO",
  "CRM",
  "Figma",
  "React",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "PostgreSQL",
  "Looker",
  "Tableau",
  "Power BI",
  "Product Management",
  "Project Management",
  "Análisis financiero",
  "Gestión de proyectos",
];

export const industryOptions = [
  "Tecnología",
  "Finanzas",
  "Fintech",
  "Salud",
  "Retail",
  "Agro",
  "Consultoría",
  "Medios",
  "Gaming",
  "Inteligencia artificial",
  "Consumo",
  "SaaS",
  "E-commerce",
  "Educación",
  "Logística",
];
