import { createFileRoute } from "@tanstack/react-router";
import { AlertCircle, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { PageShell, SiteHeader } from "@/components/aplica";
import { applications, type ApplicationStatus } from "@/lib/aplica-data";
import { cn } from "@/lib/utils";
export const Route = createFileRoute("/applications")({ head: () => ({ meta: [{ title: "Tus aplicaciones — aplica" }, { name: "description", content: "Seguimiento claro de todas tus postulaciones." }, { property: "og:title", content: "Tus aplicaciones — aplica" }, { property: "og:description", content: "Revisá el estado real de cada postulación." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Applications });
function Applications() { const [filter, setFilter] = useState<string>("Todas"); const filters = ["Todas", "Enviadas", "Necesitan atención", "Entrevistas", "Rechazadas", "Archivadas"]; const filtered = filter === "Todas" ? applications : applications.filter((a) => a.status === filter.slice(0, -1) || a.status === filter); return <div className="min-h-screen"><SiteHeader/><PageShell><h1 className="text-3xl font-medium tracking-normal md:text-[40px]">Tus aplicaciones</h1><p className="mt-3 text-sm text-muted-foreground">Cada estado refleja lo que realmente pasó.</p><div className="mt-8 flex gap-2 overflow-x-auto border-b border-border pb-3">{filters.map((f) => <button key={f} onClick={() => setFilter(f)} className={cn("whitespace-nowrap rounded-full px-3 py-2 text-sm", filter === f ? "bg-foreground text-background" : "text-muted-foreground hover:bg-muted")}>{f}</button>)}</div><div>{filtered.map((a) => <article key={a.id} className="grid gap-4 border-b border-border py-5 md:grid-cols-[1fr_130px_140px_100px] md:items-center"><div className="flex gap-4"><div className="flex h-10 w-10 items-center justify-center rounded-lg border border-border bg-surface text-xs font-semibold">{a.initials}</div><div><h2 className="font-medium">{a.role}</h2><p className="mt-1 text-sm text-muted-foreground">{a.company} · {a.source}</p></div></div><p className="text-sm text-muted-foreground">{a.date}</p><p className="text-sm text-muted-foreground">{a.cv}</p><div><Status value={a.status}/><p className="mt-1 text-xs text-muted-foreground">{a.match}% match</p></div></article>)}</div></PageShell></div>; }
function Status({ value }: { value: ApplicationStatus }) { const attention = value === "Necesita atención"; return <span className={cn("inline-flex items-center gap-1.5 text-xs font-medium", attention ? "text-caution" : value === "Entrevista" ? "text-primary" : "text-muted-foreground")}>{attention ? <AlertCircle className="h-3.5 w-3.5"/> : <CheckCircle2 className="h-3.5 w-3.5"/>}{value}</span>; }
