import { createFileRoute } from "@tanstack/react-router";
import { Bell, CreditCard, Lock, Trash2 } from "lucide-react";
import { PageShell, SiteHeader } from "@/components/aplica";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import type { ReactNode } from "react";
export const Route = createFileRoute("/settings")({ head: () => ({ meta: [{ title: "Configuración — aplica" }, { name: "description", content: "Administrá notificaciones, privacidad y suscripción." }, { property: "og:title", content: "Configuración — aplica" }, { property: "og:description", content: "Controlá cómo funciona Aplica para vos." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Settings });
function Settings() { return <div className="min-h-screen"><SiteHeader/><PageShell className="max-w-[760px]"><h1 className="text-3xl font-medium tracking-normal">Configuración</h1><div className="mt-10 space-y-10"><Section icon={<Bell/>} title="WhatsApp y notificaciones"><Setting label="Resumen diario de aplicaciones"/><Setting label="Preguntas que necesitan tu atención"/><Setting label="Nuevos matches excelentes"/></Section><Section icon={<CreditCard/>} title="Suscripción"><p className="text-sm text-muted-foreground">Plan demostrativo · Sin cobros activos</p><Button variant="outline" size="sm" className="mt-4">Administrar plan</Button></Section><Section icon={<Lock/>} title="Privacidad"><Setting label="Usar mi perfil sólo en trabajos seleccionados"/><Setting label="Guardar historial de CV adaptados"/></Section><Section icon={<Trash2/>} title="Eliminar cuenta"><p className="text-sm leading-6 text-muted-foreground">Elimina tu perfil, CV, respuestas e historial. Esta acción no se puede deshacer.</p><Button variant="destructive" size="sm" className="mt-4">Eliminar mi cuenta</Button></Section></div></PageShell></div>; }
function Section({ icon, title, children }: { icon: ReactNode; title: string; children: ReactNode }) { return <section className="border-t border-border pt-6"><div className="mb-5 flex items-center gap-3 [&_svg]:h-5 [&_svg]:w-5"><span className="text-muted-foreground">{icon}</span><h2 className="font-medium">{title}</h2></div>{children}</section>; }
function Setting({ label }: { label: string }) { return <div className="flex items-center justify-between border-b border-border py-4 text-sm"><span>{label}</span><Switch defaultChecked/></div>; }
