/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApplyingRouteImport } from './routes/_authenticated/applying'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ApiPublicWorkerClaimApplicationRouteImport } from './routes/api/public/worker/claim-application'
import { Route as ApiPublicWorkerCreateUploadRouteImport } from './routes/api/public/worker/create-upload'
import { Route as ApiPublicWorkerHeartbeatRouteImport } from './routes/api/public/worker/heartbeat'
import { Route as ApiPublicWorkerInspectionsClaimRouteImport } from './routes/api/public/worker/inspections.claim'
import { Route as ApiPublicWorkerJobsClaimRouteImport } from './routes/api/public/worker/jobs.claim'
import { Route as ApiPublicWorkerInspectionsIdResultRouteImport } from './routes/api/public/worker/inspections.$id.result'
import { Route as ApiPublicWorkerJobsIdFailureRouteImport } from './routes/api/public/worker/jobs.$id.failure'
import { Route as ApiPublicWorkerJobsIdStatusRouteImport } from './routes/api/public/worker/jobs.$id.status'
import { Route as ApiPublicWorkerJobsIdSubmissionRouteImport } from './routes/api/public/worker/jobs.$id.submission'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyingRoute = AuthenticatedApplyingRouteImport.update({
  id: '/applying',
  path: '/applying',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const ApiPublicWorkerClaimApplicationRoute =
  ApiPublicWorkerClaimApplicationRouteImport.update({
    id: '/api/public/worker/claim-application',
    path: '/api/public/worker/claim-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerCreateUploadRoute =
  ApiPublicWorkerCreateUploadRouteImport.update({
    id: '/api/public/worker/create-upload',
    path: '/api/public/worker/create-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerHeartbeatRoute =
  ApiPublicWorkerHeartbeatRouteImport.update({
    id: '/api/public/worker/heartbeat',
    path: '/api/public/worker/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerInspectionsClaimRoute =
  ApiPublicWorkerInspectionsClaimRouteImport.update({
    id: '/api/public/worker/inspections/claim',
    path: '/api/public/worker/inspections/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerJobsClaimRoute =
  ApiPublicWorkerJobsClaimRouteImport.update({
    id: '/api/public/worker/jobs/claim',
    path: '/api/public/worker/jobs/claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerInspectionsIdResultRoute =
  ApiPublicWorkerInspectionsIdResultRouteImport.update({
    id: '/api/public/worker/inspections/$id/result',
    path: '/api/public/worker/inspections/$id/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerJobsIdFailureRoute =
  ApiPublicWorkerJobsIdFailureRouteImport.update({
    id: '/api/public/worker/jobs/$id/failure',
    path: '/api/public/worker/jobs/$id/failure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerJobsIdStatusRoute =
  ApiPublicWorkerJobsIdStatusRouteImport.update({
    id: '/api/public/worker/jobs/$id/status',
    path: '/api/public/worker/jobs/$id/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWorkerJobsIdSubmissionRoute =
  ApiPublicWorkerJobsIdSubmissionRouteImport.update({
    id: '/api/public/worker/jobs/$id/submission',
    path: '/api/public/worker/jobs/$id/submission',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/applying': typeof AuthenticatedApplyingRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/worker/claim-application': typeof ApiPublicWorkerClaimApplicationRoute
  '/api/public/worker/create-upload': typeof ApiPublicWorkerCreateUploadRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/inspections/claim': typeof ApiPublicWorkerInspectionsClaimRoute
  '/api/public/worker/jobs/claim': typeof ApiPublicWorkerJobsClaimRoute
  '/api/public/worker/inspections/$id/result': typeof ApiPublicWorkerInspectionsIdResultRoute
  '/api/public/worker/jobs/$id/failure': typeof ApiPublicWorkerJobsIdFailureRoute
  '/api/public/worker/jobs/$id/status': typeof ApiPublicWorkerJobsIdStatusRoute
  '/api/public/worker/jobs/$id/submission': typeof ApiPublicWorkerJobsIdSubmissionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/applying': typeof AuthenticatedApplyingRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/worker/claim-application': typeof ApiPublicWorkerClaimApplicationRoute
  '/api/public/worker/create-upload': typeof ApiPublicWorkerCreateUploadRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/inspections/claim': typeof ApiPublicWorkerInspectionsClaimRoute
  '/api/public/worker/jobs/claim': typeof ApiPublicWorkerJobsClaimRoute
  '/api/public/worker/inspections/$id/result': typeof ApiPublicWorkerInspectionsIdResultRoute
  '/api/public/worker/jobs/$id/failure': typeof ApiPublicWorkerJobsIdFailureRoute
  '/api/public/worker/jobs/$id/status': typeof ApiPublicWorkerJobsIdStatusRoute
  '/api/public/worker/jobs/$id/submission': typeof ApiPublicWorkerJobsIdSubmissionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/applications': typeof ApplicationsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/upgrade': typeof UpgradeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/applying': typeof AuthenticatedApplyingRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/worker/claim-application': typeof ApiPublicWorkerClaimApplicationRoute
  '/api/public/worker/create-upload': typeof ApiPublicWorkerCreateUploadRoute
  '/api/public/worker/heartbeat': typeof ApiPublicWorkerHeartbeatRoute
  '/api/public/worker/inspections/claim': typeof ApiPublicWorkerInspectionsClaimRoute
  '/api/public/worker/jobs/claim': typeof ApiPublicWorkerJobsClaimRoute
  '/api/public/worker/inspections/$id/result': typeof ApiPublicWorkerInspectionsIdResultRoute
  '/api/public/worker/jobs/$id/failure': typeof ApiPublicWorkerJobsIdFailureRoute
  '/api/public/worker/jobs/$id/status': typeof ApiPublicWorkerJobsIdStatusRoute
  '/api/public/worker/jobs/$id/submission': typeof ApiPublicWorkerJobsIdSubmissionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/upgrade'
    | '/admin'
    | '/applying'
    | '/jobs/$id'
    | '/api/public/worker/claim-application'
    | '/api/public/worker/create-upload'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/inspections/claim'
    | '/api/public/worker/jobs/claim'
    | '/api/public/worker/inspections/$id/result'
    | '/api/public/worker/jobs/$id/failure'
    | '/api/public/worker/jobs/$id/status'
    | '/api/public/worker/jobs/$id/submission'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/upgrade'
    | '/admin'
    | '/applying'
    | '/jobs/$id'
    | '/api/public/worker/claim-application'
    | '/api/public/worker/create-upload'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/inspections/claim'
    | '/api/public/worker/jobs/claim'
    | '/api/public/worker/inspections/$id/result'
    | '/api/public/worker/jobs/$id/failure'
    | '/api/public/worker/jobs/$id/status'
    | '/api/public/worker/jobs/$id/submission'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/applications'
    | '/jobs'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/upgrade'
    | '/_authenticated/admin'
    | '/_authenticated/applying'
    | '/jobs/$id'
    | '/api/public/worker/claim-application'
    | '/api/public/worker/create-upload'
    | '/api/public/worker/heartbeat'
    | '/api/public/worker/inspections/claim'
    | '/api/public/worker/jobs/claim'
    | '/api/public/worker/inspections/$id/result'
    | '/api/public/worker/jobs/$id/failure'
    | '/api/public/worker/jobs/$id/status'
    | '/api/public/worker/jobs/$id/submission'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApplicationsRoute: typeof ApplicationsRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  UpgradeRoute: typeof UpgradeRoute
  ApiPublicWorkerClaimApplicationRoute: typeof ApiPublicWorkerClaimApplicationRoute
  ApiPublicWorkerCreateUploadRoute: typeof ApiPublicWorkerCreateUploadRoute
  ApiPublicWorkerHeartbeatRoute: typeof ApiPublicWorkerHeartbeatRoute
  ApiPublicWorkerInspectionsClaimRoute: typeof ApiPublicWorkerInspectionsClaimRoute
  ApiPublicWorkerJobsClaimRoute: typeof ApiPublicWorkerJobsClaimRoute
  ApiPublicWorkerInspectionsIdResultRoute: typeof ApiPublicWorkerInspectionsIdResultRoute
  ApiPublicWorkerJobsIdFailureRoute: typeof ApiPublicWorkerJobsIdFailureRoute
  ApiPublicWorkerJobsIdStatusRoute: typeof ApiPublicWorkerJobsIdStatusRoute
  ApiPublicWorkerJobsIdSubmissionRoute: typeof ApiPublicWorkerJobsIdSubmissionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applying': {
      id: '/_authenticated/applying'
      path: '/applying'
      fullPath: '/applying'
      preLoaderRoute: typeof AuthenticatedApplyingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/api/public/worker/claim-application': {
      id: '/api/public/worker/claim-application'
      path: '/api/public/worker/claim-application'
      fullPath: '/api/public/worker/claim-application'
      preLoaderRoute: typeof ApiPublicWorkerClaimApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/create-upload': {
      id: '/api/public/worker/create-upload'
      path: '/api/public/worker/create-upload'
      fullPath: '/api/public/worker/create-upload'
      preLoaderRoute: typeof ApiPublicWorkerCreateUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/heartbeat': {
      id: '/api/public/worker/heartbeat'
      path: '/api/public/worker/heartbeat'
      fullPath: '/api/public/worker/heartbeat'
      preLoaderRoute: typeof ApiPublicWorkerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/inspections/claim': {
      id: '/api/public/worker/inspections/claim'
      path: '/api/public/worker/inspections/claim'
      fullPath: '/api/public/worker/inspections/claim'
      preLoaderRoute: typeof ApiPublicWorkerInspectionsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/jobs/claim': {
      id: '/api/public/worker/jobs/claim'
      path: '/api/public/worker/jobs/claim'
      fullPath: '/api/public/worker/jobs/claim'
      preLoaderRoute: typeof ApiPublicWorkerJobsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/inspections/$id/result': {
      id: '/api/public/worker/inspections/$id/result'
      path: '/api/public/worker/inspections/$id/result'
      fullPath: '/api/public/worker/inspections/$id/result'
      preLoaderRoute: typeof ApiPublicWorkerInspectionsIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/jobs/$id/failure': {
      id: '/api/public/worker/jobs/$id/failure'
      path: '/api/public/worker/jobs/$id/failure'
      fullPath: '/api/public/worker/jobs/$id/failure'
      preLoaderRoute: typeof ApiPublicWorkerJobsIdFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/jobs/$id/status': {
      id: '/api/public/worker/jobs/$id/status'
      path: '/api/public/worker/jobs/$id/status'
      fullPath: '/api/public/worker/jobs/$id/status'
      preLoaderRoute: typeof ApiPublicWorkerJobsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/worker/jobs/$id/submission': {
      id: '/api/public/worker/jobs/$id/submission'
      path: '/api/public/worker/jobs/$id/submission'
      fullPath: '/api/public/worker/jobs/$id/submission'
      preLoaderRoute: typeof ApiPublicWorkerJobsIdSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApplyingRoute: typeof AuthenticatedApplyingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApplyingRoute: AuthenticatedApplyingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApplicationsRoute: ApplicationsRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  UpgradeRoute: UpgradeRoute,
  ApiPublicWorkerClaimApplicationRoute: ApiPublicWorkerClaimApplicationRoute,
  ApiPublicWorkerCreateUploadRoute: ApiPublicWorkerCreateUploadRoute,
  ApiPublicWorkerHeartbeatRoute: ApiPublicWorkerHeartbeatRoute,
  ApiPublicWorkerInspectionsClaimRoute: ApiPublicWorkerInspectionsClaimRoute,
  ApiPublicWorkerJobsClaimRoute: ApiPublicWorkerJobsClaimRoute,
  ApiPublicWorkerInspectionsIdResultRoute:
    ApiPublicWorkerInspectionsIdResultRoute,
  ApiPublicWorkerJobsIdFailureRoute: ApiPublicWorkerJobsIdFailureRoute,
  ApiPublicWorkerJobsIdStatusRoute: ApiPublicWorkerJobsIdStatusRoute,
  ApiPublicWorkerJobsIdSubmissionRoute: ApiPublicWorkerJobsIdSubmissionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
